/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTransactionModel,
  ErrorResponse,
  TransactionsPost200Response,
} from '../models/index';
import {
    CreateTransactionModelFromJSON,
    CreateTransactionModelToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TransactionsPost200ResponseFromJSON,
    TransactionsPost200ResponseToJSON,
} from '../models/index';

export interface TransactionsPostRequest {
    createTransactionModel: CreateTransactionModel;
}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI {

    /**
     * Create a new transaction
     */
    async transactionsPostRaw(requestParameters: TransactionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsPost200Response>> {
        if (requestParameters['createTransactionModel'] == null) {
            throw new runtime.RequiredError(
                'createTransactionModel',
                'Required parameter "createTransactionModel" was null or undefined when calling transactionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transactions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransactionModelToJSON(requestParameters['createTransactionModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new transaction
     */
    async transactionsPost(requestParameters: TransactionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsPost200Response> {
        const response = await this.transactionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
