/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface AuthLoginPost200Response
 */
export interface AuthLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLoginPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {LoginResponse}
     * @memberof AuthLoginPost200Response
     */
    data?: LoginResponse;
}

/**
 * Check if a given object implements the AuthLoginPost200Response interface.
 */
export function instanceOfAuthLoginPost200Response(value: object): value is AuthLoginPost200Response {
    return true;
}

export function AuthLoginPost200ResponseFromJSON(json: any): AuthLoginPost200Response {
    return AuthLoginPost200ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
    };
}

export function AuthLoginPost200ResponseToJSON(json: any): AuthLoginPost200Response {
    return AuthLoginPost200ResponseToJSONTyped(json, false);
}

export function AuthLoginPost200ResponseToJSONTyped(value?: AuthLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': LoginResponseToJSON(value['data']),
    };
}

