/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConfigDatesResponse
 */
export interface GetConfigDatesResponse {
    /**
     * 
     * @type {Array<number>}
     * @memberof GetConfigDatesResponse
     */
    months?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GetConfigDatesResponse
     */
    years?: Array<number>;
}

/**
 * Check if a given object implements the GetConfigDatesResponse interface.
 */
export function instanceOfGetConfigDatesResponse(value: object): value is GetConfigDatesResponse {
    return true;
}

export function GetConfigDatesResponseFromJSON(json: any): GetConfigDatesResponse {
    return GetConfigDatesResponseFromJSONTyped(json, false);
}

export function GetConfigDatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigDatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'months': json['months'] == null ? undefined : json['months'],
        'years': json['years'] == null ? undefined : json['years'],
    };
}

export function GetConfigDatesResponseToJSON(json: any): GetConfigDatesResponse {
    return GetConfigDatesResponseToJSONTyped(json, false);
}

export function GetConfigDatesResponseToJSONTyped(value?: GetConfigDatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'months': value['months'],
        'years': value['years'],
    };
}

