/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableTypeEntity
 */
export interface TableTypeEntity {
    /**
     * 
     * @type {number}
     * @memberof TableTypeEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TableTypeEntity
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof TableTypeEntity
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TableTypeEntity
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TableTypeEntity
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TableTypeEntity
     */
    updated_at?: string;
}

/**
 * Check if a given object implements the TableTypeEntity interface.
 */
export function instanceOfTableTypeEntity(value: object): value is TableTypeEntity {
    return true;
}

export function TableTypeEntityFromJSON(json: any): TableTypeEntity {
    return TableTypeEntityFromJSONTyped(json, false);
}

export function TableTypeEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableTypeEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function TableTypeEntityToJSON(json: any): TableTypeEntity {
    return TableTypeEntityToJSONTyped(json, false);
}

export function TableTypeEntityToJSONTyped(value?: TableTypeEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'description': value['description'],
        'status': value['status'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
    };
}

