/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableEntity } from './TableEntity';
import {
    TableEntityFromJSON,
    TableEntityFromJSONTyped,
    TableEntityToJSON,
    TableEntityToJSONTyped,
} from './TableEntity';

/**
 * 
 * @export
 * @interface TablesPost200Response
 */
export interface TablesPost200Response {
    /**
     * 
     * @type {string}
     * @memberof TablesPost200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TablesPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {TableEntity}
     * @memberof TablesPost200Response
     */
    data?: TableEntity;
}

/**
 * Check if a given object implements the TablesPost200Response interface.
 */
export function instanceOfTablesPost200Response(value: object): value is TablesPost200Response {
    return true;
}

export function TablesPost200ResponseFromJSON(json: any): TablesPost200Response {
    return TablesPost200ResponseFromJSONTyped(json, false);
}

export function TablesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TablesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : TableEntityFromJSON(json['data']),
    };
}

export function TablesPost200ResponseToJSON(json: any): TablesPost200Response {
    return TablesPost200ResponseToJSONTyped(json, false);
}

export function TablesPost200ResponseToJSONTyped(value?: TablesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': TableEntityToJSON(value['data']),
    };
}

