/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionEntity } from './TransactionEntity';
import {
    TransactionEntityFromJSON,
    TransactionEntityFromJSONTyped,
    TransactionEntityToJSON,
    TransactionEntityToJSONTyped,
} from './TransactionEntity';

/**
 * 
 * @export
 * @interface TransactionsPost200Response
 */
export interface TransactionsPost200Response {
    /**
     * 
     * @type {string}
     * @memberof TransactionsPost200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {TransactionEntity}
     * @memberof TransactionsPost200Response
     */
    data?: TransactionEntity;
}

/**
 * Check if a given object implements the TransactionsPost200Response interface.
 */
export function instanceOfTransactionsPost200Response(value: object): value is TransactionsPost200Response {
    return true;
}

export function TransactionsPost200ResponseFromJSON(json: any): TransactionsPost200Response {
    return TransactionsPost200ResponseFromJSONTyped(json, false);
}

export function TransactionsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : TransactionEntityFromJSON(json['data']),
    };
}

export function TransactionsPost200ResponseToJSON(json: any): TransactionsPost200Response {
    return TransactionsPost200ResponseToJSONTyped(json, false);
}

export function TransactionsPost200ResponseToJSONTyped(value?: TransactionsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': TransactionEntityToJSON(value['data']),
    };
}

