/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTransactionDto
 */
export interface UpdateTransactionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionDto
     */
    type_id?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionDto
     */
    date?: string;
}

/**
 * Check if a given object implements the UpdateTransactionDto interface.
 */
export function instanceOfUpdateTransactionDto(value: object): value is UpdateTransactionDto {
    return true;
}

export function UpdateTransactionDtoFromJSON(json: any): UpdateTransactionDto {
    return UpdateTransactionDtoFromJSONTyped(json, false);
}

export function UpdateTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'type_id': json['type_id'] == null ? undefined : json['type_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function UpdateTransactionDtoToJSON(json: any): UpdateTransactionDto {
    return UpdateTransactionDtoToJSONTyped(json, false);
}

export function UpdateTransactionDtoToJSONTyped(value?: UpdateTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'type_id': value['type_id'],
        'amount': value['amount'],
        'date': value['date'],
    };
}

