/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConfigResponse } from './GetConfigResponse';
import {
    GetConfigResponseFromJSON,
    GetConfigResponseFromJSONTyped,
    GetConfigResponseToJSON,
    GetConfigResponseToJSONTyped,
} from './GetConfigResponse';

/**
 * 
 * @export
 * @interface ConfigGet200Response
 */
export interface ConfigGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ConfigGet200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetConfigResponse}
     * @memberof ConfigGet200Response
     */
    data?: GetConfigResponse;
}

/**
 * Check if a given object implements the ConfigGet200Response interface.
 */
export function instanceOfConfigGet200Response(value: object): value is ConfigGet200Response {
    return true;
}

export function ConfigGet200ResponseFromJSON(json: any): ConfigGet200Response {
    return ConfigGet200ResponseFromJSONTyped(json, false);
}

export function ConfigGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : GetConfigResponseFromJSON(json['data']),
    };
}

export function ConfigGet200ResponseToJSON(json: any): ConfigGet200Response {
    return ConfigGet200ResponseToJSONTyped(json, false);
}

export function ConfigGet200ResponseToJSONTyped(value?: ConfigGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': GetConfigResponseToJSON(value['data']),
    };
}

