/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransactionModel
 */
export interface CreateTransactionModel {
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionModel
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionModel
     */
    table_id?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionModel
     */
    type_id?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionModel
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionModel
     */
    currency_id?: number;
}

/**
 * Check if a given object implements the CreateTransactionModel interface.
 */
export function instanceOfCreateTransactionModel(value: object): value is CreateTransactionModel {
    return true;
}

export function CreateTransactionModelFromJSON(json: any): CreateTransactionModel {
    return CreateTransactionModelFromJSONTyped(json, false);
}

export function CreateTransactionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'table_id': json['table_id'] == null ? undefined : json['table_id'],
        'type_id': json['type_id'] == null ? undefined : json['type_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency_id': json['currency_id'] == null ? undefined : json['currency_id'],
    };
}

export function CreateTransactionModelToJSON(json: any): CreateTransactionModel {
    return CreateTransactionModelToJSONTyped(json, false);
}

export function CreateTransactionModelToJSONTyped(value?: CreateTransactionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'table_id': value['table_id'],
        'type_id': value['type_id'],
        'amount': value['amount'],
        'currency_id': value['currency_id'],
    };
}

