/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTableModel
 */
export interface CreateTableModel {
    /**
     * 
     * @type {number}
     * @memberof CreateTableModel
     */
    user_id: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTableModel
     */
    type_id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTableModel
     */
    month_year: string;
}

/**
 * Check if a given object implements the CreateTableModel interface.
 */
export function instanceOfCreateTableModel(value: object): value is CreateTableModel {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('type_id' in value) || value['type_id'] === undefined) return false;
    if (!('month_year' in value) || value['month_year'] === undefined) return false;
    return true;
}

export function CreateTableModelFromJSON(json: any): CreateTableModel {
    return CreateTableModelFromJSONTyped(json, false);
}

export function CreateTableModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTableModel {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'type_id': json['type_id'],
        'month_year': json['month_year'],
    };
}

export function CreateTableModelToJSON(json: any): CreateTableModel {
    return CreateTableModelToJSONTyped(json, false);
}

export function CreateTableModelToJSONTyped(value?: CreateTableModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'type_id': value['type_id'],
        'month_year': value['month_year'],
    };
}

