/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyEntity
 */
export interface CurrencyEntity {
    /**
     * 
     * @type {number}
     * @memberof CurrencyEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyEntity
     */
    abbreviation?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyEntity
     */
    symbol?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CurrencyEntity
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CurrencyEntity
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyEntity
     */
    updated_at?: string;
}

/**
 * Check if a given object implements the CurrencyEntity interface.
 */
export function instanceOfCurrencyEntity(value: object): value is CurrencyEntity {
    return true;
}

export function CurrencyEntityFromJSON(json: any): CurrencyEntity {
    return CurrencyEntityFromJSONTyped(json, false);
}

export function CurrencyEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'status': json['status'] == null ? undefined : json['status'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function CurrencyEntityToJSON(json: any): CurrencyEntity {
    return CurrencyEntityToJSONTyped(json, false);
}

export function CurrencyEntityToJSONTyped(value?: CurrencyEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'abbreviation': value['abbreviation'],
        'symbol': value['symbol'],
        'status': value['status'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
    };
}

