/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConfigDatesResponse } from './GetConfigDatesResponse';
import {
    GetConfigDatesResponseFromJSON,
    GetConfigDatesResponseFromJSONTyped,
    GetConfigDatesResponseToJSON,
    GetConfigDatesResponseToJSONTyped,
} from './GetConfigDatesResponse';
import type { CurrencyEntity } from './CurrencyEntity';
import {
    CurrencyEntityFromJSON,
    CurrencyEntityFromJSONTyped,
    CurrencyEntityToJSON,
    CurrencyEntityToJSONTyped,
} from './CurrencyEntity';
import type { TransactionTypeEntity } from './TransactionTypeEntity';
import {
    TransactionTypeEntityFromJSON,
    TransactionTypeEntityFromJSONTyped,
    TransactionTypeEntityToJSON,
    TransactionTypeEntityToJSONTyped,
} from './TransactionTypeEntity';

/**
 * 
 * @export
 * @interface GetConfigResponse
 */
export interface GetConfigResponse {
    /**
     * 
     * @type {Array<CurrencyEntity>}
     * @memberof GetConfigResponse
     */
    currencies?: Array<CurrencyEntity>;
    /**
     * 
     * @type {Array<TransactionTypeEntity>}
     * @memberof GetConfigResponse
     */
    transaction_types?: Array<TransactionTypeEntity>;
    /**
     * 
     * @type {GetConfigDatesResponse}
     * @memberof GetConfigResponse
     */
    month_years?: GetConfigDatesResponse;
}

/**
 * Check if a given object implements the GetConfigResponse interface.
 */
export function instanceOfGetConfigResponse(value: object): value is GetConfigResponse {
    return true;
}

export function GetConfigResponseFromJSON(json: any): GetConfigResponse {
    return GetConfigResponseFromJSONTyped(json, false);
}

export function GetConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currencies': json['currencies'] == null ? undefined : ((json['currencies'] as Array<any>).map(CurrencyEntityFromJSON)),
        'transaction_types': json['transaction_types'] == null ? undefined : ((json['transaction_types'] as Array<any>).map(TransactionTypeEntityFromJSON)),
        'month_years': json['month_years'] == null ? undefined : GetConfigDatesResponseFromJSON(json['month_years']),
    };
}

export function GetConfigResponseToJSON(json: any): GetConfigResponse {
    return GetConfigResponseToJSONTyped(json, false);
}

export function GetConfigResponseToJSONTyped(value?: GetConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currencies': value['currencies'] == null ? undefined : ((value['currencies'] as Array<any>).map(CurrencyEntityToJSON)),
        'transaction_types': value['transaction_types'] == null ? undefined : ((value['transaction_types'] as Array<any>).map(TransactionTypeEntityToJSON)),
        'month_years': GetConfigDatesResponseToJSON(value['month_years']),
    };
}

