/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetTableByIdResponse } from './GetTableByIdResponse';
import {
    GetTableByIdResponseFromJSON,
    GetTableByIdResponseFromJSONTyped,
    GetTableByIdResponseToJSON,
    GetTableByIdResponseToJSONTyped,
} from './GetTableByIdResponse';

/**
 * 
 * @export
 * @interface TablesIdGet200Response
 */
export interface TablesIdGet200Response {
    /**
     * 
     * @type {string}
     * @memberof TablesIdGet200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TablesIdGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetTableByIdResponse}
     * @memberof TablesIdGet200Response
     */
    data?: GetTableByIdResponse;
}

/**
 * Check if a given object implements the TablesIdGet200Response interface.
 */
export function instanceOfTablesIdGet200Response(value: object): value is TablesIdGet200Response {
    return true;
}

export function TablesIdGet200ResponseFromJSON(json: any): TablesIdGet200Response {
    return TablesIdGet200ResponseFromJSONTyped(json, false);
}

export function TablesIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TablesIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : GetTableByIdResponseFromJSON(json['data']),
    };
}

export function TablesIdGet200ResponseToJSON(json: any): TablesIdGet200Response {
    return TablesIdGet200ResponseToJSONTyped(json, false);
}

export function TablesIdGet200ResponseToJSONTyped(value?: TablesIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': GetTableByIdResponseToJSON(value['data']),
    };
}

