/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionsIdDelete200Response
 */
export interface TransactionsIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof TransactionsIdDelete200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsIdDelete200Response
     */
    success?: boolean;
    /**
     * 
     * @type {object}
     * @memberof TransactionsIdDelete200Response
     */
    data?: object;
}

/**
 * Check if a given object implements the TransactionsIdDelete200Response interface.
 */
export function instanceOfTransactionsIdDelete200Response(value: object): value is TransactionsIdDelete200Response {
    return true;
}

export function TransactionsIdDelete200ResponseFromJSON(json: any): TransactionsIdDelete200Response {
    return TransactionsIdDelete200ResponseFromJSONTyped(json, false);
}

export function TransactionsIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function TransactionsIdDelete200ResponseToJSON(json: any): TransactionsIdDelete200Response {
    return TransactionsIdDelete200ResponseToJSONTyped(json, false);
}

export function TransactionsIdDelete200ResponseToJSONTyped(value?: TransactionsIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'data': value['data'],
    };
}

