/* tslint:disable */
/* eslint-disable */
/**
 * sp_internal_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionEntity
 */
export interface TransactionEntity {
    /**
     * 
     * @type {number}
     * @memberof TransactionEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntity
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntity
     */
    type_id?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntity
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntity
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntity
     */
    currency_id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionEntity
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntity
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntity
     */
    updated_at?: string;
}

/**
 * Check if a given object implements the TransactionEntity interface.
 */
export function instanceOfTransactionEntity(value: object): value is TransactionEntity {
    return true;
}

export function TransactionEntityFromJSON(json: any): TransactionEntity {
    return TransactionEntityFromJSONTyped(json, false);
}

export function TransactionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'type_id': json['type_id'] == null ? undefined : json['type_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': json['date'] == null ? undefined : json['date'],
        'currency_id': json['currency_id'] == null ? undefined : json['currency_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function TransactionEntityToJSON(json: any): TransactionEntity {
    return TransactionEntityToJSONTyped(json, false);
}

export function TransactionEntityToJSONTyped(value?: TransactionEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'type_id': value['type_id'],
        'amount': value['amount'],
        'date': value['date'],
        'currency_id': value['currency_id'],
        'status': value['status'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
    };
}

